version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - '3000:80'

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MOVIE_API_KEY=${MOVIE_API_KEY}
    ports:
      - '5000:80'
    depends_on:
      - seq

  seq:
    image: datalust/seq:latest
    ports:
      - '5341:80'
